### ISSUE TITLE
External MCU application update not working

### ISSUE THREAD

**Issue by nishithvpoojary** [Azure/azure-sphere-samples#215]
Hello,
I use Avnet Starter kit Rev2 and nrf52840 development board.
I used the External MCU update code.
I am not able to send the firmware to nrf52. I get this below issue.
![image](https://user-images.githubusercontent.com/45986919/131652537-1fb8cbba-28db-48c5-98bf-61f707682802.png)
![image](https://user-images.githubusercontent.com/45986919/131652739-ecdf8f96-39e3-4132-af7f-25e615ee2c22.png)
![image](https://user-images.githubusercontent.com/45986919/131652833-cdb85834-1ffd-4c6c-973c-98bde2972b7c.png)

Please help me out with this issue. Thank you

**Comment by bawilless** [comment]
Were you able to run the https://github.com/Azure/azure-sphere-samples/tree/master/Samples/ExternalMcuUpdate example on the Starter Kit Rev2 without any modifications?

**Comment by nishithvpoojary** [comment]
> Were you able to run the https://github.com/Azure/azure-sphere-samples/tree/master/Samples/ExternalMcuUpdate example on the Starter Kit Rev2 without any modifications?

I had make few modifications. Used softdevice140 instead of s132. Changed hardware settings required for Avnet rev2 board.
Removed nRFReset  by pin functions and added json data which is sent to nrf52. When the nrf52 receives this json data, the device goes to bootloader mode.

**Comment by nishithvpoojary** [comment]
What should I do for this softdevice issue?

**Comment by gtrevi** [comment]
@nishithvpoojary 
This issue has not much relation to the Azure Sphere updating sample itself, since the softdevice upgrade validation is done on the nRF bootloader (`nrf_dfu_validation.c` & `nrf_dfu_ver_validation.c`). Clearly, if is not supplied in the update batch, the problem does not arise.

S140 should be in fact compatible with the nRF52840 SoC (see [here](https://www.nordicsemi.com/Products/Development-software/S140)), so I suggest checking out on the nRF documentation and bootloader source code to verify the available options.
Also, the bootloader itself should emit debug logs, from where you can check the code-paths taken for the softdevice validation that is failing (see [here](https://devzone.nordicsemi.com/f/nordic-q-a/16979/where-can-i-see-nrf_log-output)).

**Comment by gtrevi** [comment]
Closing this. Feel free to follow-up in case needed.
